"""empty message

Revision ID: c880fe65cb8f
Revises: 6f8190f17674
Create Date: 2021-06-03 17:17:38.031954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c880fe65cb8f'
down_revision = '6f8190f17674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('place', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('agent')

    op.drop_table('meetings')
    # ### end Alembic commands ###
