"""empty message

Revision ID: cbad0bf5c5db
Revises: d2b32a6efd66
Create Date: 2021-06-07 21:27:01.514523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbad0bf5c5db'
down_revision = 'd2b32a6efd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.drop_column('state_data')
        batch_op.drop_column('state')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
